### ISSUE TITLE
Message: 'FileReader' is undefined

### ISSUE THREAD

**Issue by bfranklin825** [TooManyBees/knockoutjs-file-binding#3]
In Internet Explorer 11 (and probably below), 

description: "'FileReader' is undefined"
message: "Unable to process binding "file: function(){return { data:FileInput,name:FileName} }"
name: "ReferenceError"
number: -2146823279

Causes file upload to not work.

**Comment by TooManyBees** [comment]
this was merely a typo in a PR I paid too little attention to; fixed.
